
DROP TABLE IF EXISTS leases
CASCADE;
CREATE TABLE leases
(
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  renter_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL,
  term_length INTEGER NOT NULL,
  total_cost NUMERIC(12, 2) NOT NULL DEFAULT 0.00
);
