
DROP TABLE IF EXISTS leases
CASCADE;
CREATE TABLE leases
(
  id SERIAL PRIMARY KEY NOT NULL,
  lot_id INTEGER REFERENCES lots(id) ON DELETE CASCADE NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  renter_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP DEFAULT current_timestamp,
  term_length INTEGER NOT NULL,
  total_cost NUMERIC(12, 2) NOT NULL DEFAULT 0.00
);
