insert into lots (id, user_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_description, is_leased, street_address, city, country, post_code, created_at, is_active) values (1, 1, 'David', 8322, 17, false, 15, 4, '6/5/2020', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', true, '2100 208 Street', ' Langley', 'Canada', 'V2Z2A6', '3/6/2020', true);

insert into lots (id, user_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_description, is_leased, street_address, city, country, post_code, created_at, is_active) values (2, 2, 'Eastlawn', 1870, 49, false, 6, 2, '8/18/2020', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', false, '21479 Smith Crescent', 'Langley', 'Canada', 'V2Y2R4', '10/15/2019', false);

insert into lots (id, user_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_description, is_leased, street_address, city, country, post_code, created_at, is_active) values (3, 1, 'Stuart', 8468, 39, true, 20, 2, '6/5/2020', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', true, '4 Jana Crossing', 'Vancouver', 'Canada', null, '5/30/2020', false);

insert into lots (id, user_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_description, is_leased, street_address, city, country, post_code, created_at, is_active) values (4, 3, '4th', 8681, 57, false, 1, 4, '8/13/2020', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', true, '071 Thackeray Parkway', 'Edmonton', 'Canada', null, '12/8/2019', true);

insert into lots (id, user_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_description, is_leased, street_address, city, country, post_code, created_at, is_active) values (5, 4, 'Northland', 458, 33, false, 18, 4, '8/10/2020', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', true, '864 Ohio Street', 'Edmonton', 'Canada', null, '7/10/2020', false);

insert into lots (id, user_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_description, is_leased, street_address, city, country, post_code, created_at, is_active) values (6, 3, 'Northland', 458, 33, false, 18, 4, '8/10/2020', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', true, '864 Ohio Street', 'Edmonton', 'Canada', null, '7/10/2020', false);