insert into lots (owner_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_type, lot_description, is_leased, street_address, city, country, post_code, created_at, is_active) values (1, 'David', 8322, 17, false, 15, 4, '6/5/2020', 'residential', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', true, '2100 208 Street', 'langley', 'canada', 'V2Z2A6', '3/6/2020', true);

insert into lots (owner_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_type,lot_description, is_leased, street_address, city, country, post_code, created_at, is_active) values (2, 'Eastlawn', 1870, 49, false, 6, 2, '8/18/2020', 'residential', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', false, '21479 Smith Crescent', 'langley', 'canada', 'V2Y2R4', '10/15/2019', false);

insert into lots (owner_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_type, lot_description, is_leased, street_address, city, country, post_code, lat, long, created_at, is_active) values (1, 'Stuart', 8468, 39, true, 20, 2, '6/5/2020', 'residential', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', true, '12040 149 St NW', 'edmonton', 'canada', 'T5V1P2', NUll, NUll, '5/30/2020', false);

insert into lots (owner_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_type, lot_description, is_leased, street_address, city, country, post_code, lat, long, created_at, is_active) values (3, '4th', 8681, 57, false, 1, 4, '8/13/2020', 'commercial', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', true, '11312 79 St NW', 'edmonton', 'canada', 'T5B2K2', NUll, NUll, '12/8/2019', true);

insert into lots (owner_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_type, lot_description, is_leased, street_address, city, country, post_code, lat, long, created_at, is_active) values (4, 'Northland', 458, 33, false, 18, 4, '8/10/2020', 'commercial', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', true, '1903 Parsons Rd NW', 'edmonton', 'canada', 'T6N1H5', NUll, NUll, '7/10/2020', false);

insert into lots (owner_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_type, lot_description, is_leased, street_address, city, country, post_code, lat, long, created_at, is_active) values (3, 'Northland', 458, 33, false, 18, 4, '8/10/2020', 'commercial', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', true, '5910 216 St', 'langley', 'canada', 'V2Y2N5', NUll, null, '7/10/2020', false);

