insert into lots (owner_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_type, lot_description, is_leased, street_address, city, country, post_code, lat, long, created_at, is_active) values (1, 'For a Serious Farmer', 2000, 17, true, 15, 4, '6/5/2020', 'residential', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', true, '2100 208 Street', 'langley', 'canada', 'V2Z2A6', 49.042960, -122.638460, '2020-03-06', true);

insert into lots (owner_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_type,lot_description, is_leased, street_address, city, country, post_code, lat, long, created_at, is_active) values (4, 'Eastlawn', 1870, 49, true, 6, 5, '8/18/2020', 'residential', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', false, '21479 Smith Crescent', 'langley', 'canada', 'V2Y2R4', 49.133890, -122.627330, '2019-10-15', true);

insert into lots (owner_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_type, lot_description, is_leased, street_address, city, country, post_code, lat, long, created_at, is_active) values (1, 'Central and Quiet', 500, 39, true, 20, 4, '6/5/2020', 'residential', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', true, '12040 149 St NW', 'edmonton', 'canada', 'T5V1P2', 53.572510, -113.578480, '2020-05-30', true);

insert into lots (owner_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_type, lot_description, is_leased, street_address, city, country, post_code, lat, long, created_at, is_active) values (3, 'Previously Organic', 1000, 57, true, 1, 4, '8/13/2020', 'residential', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', true, '11312 79 St NW', 'edmonton', 'canada', 'T5B2K2', 53.563140, -113.462770, '2019-12-08', true);

insert into lots (owner_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_type, lot_description, is_leased, street_address, city, country, post_code, lat, long, created_at, is_active) values (4, 'Front and Backyard', 458, 33, true, 18, 4, '8/10/2020', 'residential', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', true, '1903 Parsons Rd NW', 'edmonton', 'canada', 'T6N1H5', 53.447780, -113.479880, '2020-07-10', true);

insert into lots (owner_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_type, lot_description, is_leased, street_address, city, country, post_code, lat, long, created_at, is_active) values (3, 'Space to be Creative!', 5000, 10, true, 6, 5, '8/20/2020', 'commercial', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', true, '5910 216 St', 'langley', 'canada', 'V2Y2N5', 49.109517, -122.6260083, '01/03/2020', true);

-- insert into lots (owner_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_type, lot_description, is_leased, street_address, city, country, post_code, lat, long, created_at, is_active) values (5, 'Gardeners welcome!', 1200, 10, true, 6, 5, '8/20/2020', 'commercial', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', true, '519 St Clarens Ave', 'toronto', 'canada', 'M6H3W4', 43.660706, -79.442342, '01/03/2018', true);

-- insert into lots (owner_id, title, size, cost_per_month, is_irrigated, suggested_term, condition_rating, available_date, lot_type, lot_description, is_leased, street_address, city, country, post_code, lat, long, created_at, is_active) values (6, 'Available Immediately', 5000, 10, true, 6, 5, '8/20/2020', 'residential', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', true, '1201-1299 Alamo St', 'austin', 'united states', '78702', 30.274600, -97.718010, '01/03/2019', true);
